# Generated by Django 5.0.1 on 2025-02-13 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_razon_social_user_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('RH', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('PROD', 'Producción'), ('TI', 'Tecnología')], default='', help_text='Área a la que pertenece el usuario', max_length=20, verbose_name='Área'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(help_text='Usuario que creó este registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='razon_social',
            field=models.CharField(choices=[('GEBESA_NACIONAL', 'GEBESA NACIONAL'), ('OPERADORA_SUCURSALES', 'OPERADORA SUCURSALES'), ('SALMON_LAGUNA', 'SALMON LAGUNA')], help_text='Razón social asociada al usuario', max_length=50, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidad',
            field=models.CharField(choices=[('CDMX', 'CDMX'), ('QRO', 'QRO'), ('LAG', 'LAG'), ('MTY', 'MTY'), ('SPL', 'SPL'), ('GDL', 'GDL')], help_text='Unidad a la que pertenece el usuario', max_length=20, verbose_name='Unidad'),
        ),
    ]
