# Generated by Django 5.0.1 on 2025-02-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_last_login_ip_alter_user_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('RH', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('PROD', 'Producción'), ('TI', 'Tecnología')], max_length=20, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='razon_social',
            field=models.CharField(blank=True, choices=[('GEBESA_NACIONAL', 'GEBESA_NACIONAL'), ('OPERADORA_SUCURSALES', 'OPERADORA_SUCURSALES'), ('SALMON_LAGUNA', 'SALMON_LAGUNA')], max_length=50, null=True, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidad',
            field=models.CharField(blank=True, choices=[('CDMX', 'CDMX'), ('QRO', 'QRO'), ('LAG', 'LAG'), ('MTY', 'MTY'), ('SPL', 'SPL'), ('GDL', 'GDL')], max_length=10, null=True, verbose_name='Unidad'),
        ),
    ]
