# Generated by Django 5.0.1 on 2025-02-18 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(32, 'Monterrey'), (43, 'CDMX'), (34, 'Querétaro'), (40, 'Laguna'), (43, 'Puebla'), (33, 'SPL'), (43, 'Guadalajara')]), blank=True, default=list, help_text='IDs de las unidades a las que pertenece el usuario', null=True, size=None, verbose_name='Unidades asignadas'),
        ),
    ]
