# Generated by Django 5.0.1 on 2025-02-20 03:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='unidades',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(32, 'Monterrey'), (33, 'SPL'), (34, 'Querétaro'), (40, 'Laguna'), (43, 'CDMX')]), blank=True, default=list, help_text='Unidades administrativas a las que pertenece el usuario', null=True, size=None),
        ),
    ]
