# Generated by Django 5.0.1 on 2025-02-26 18:36

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_bio_alter_userprofile_unidades'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_corto', models.CharField(help_text='Nombre corto o comercial de la unidad', max_length=100, unique=True)),
                ('razon_social', models.CharField(choices=[('MPF', 'Manufacturas Post Form S.A. de C.V.'), ('SLL', 'Salmon De La Laguna S.A. de C.V.'), ('OSG', 'Operadora de Sucursales Gebesa S.A. de C.V.'), ('GNA', 'GEBESA NACIONAL')], help_text='Razón social de la unidad', max_length=3)),
                ('tipo', models.CharField(choices=[('PROPIA', 'Propia'), ('DISTRIBUIDORA', 'Distribuidora'), ('CONCESIONARIO', 'Concesionario')], help_text='Tipo de unidad (propia, distribuidora, concesionario)', max_length=15)),
                ('nombre_cliente_final', models.CharField(blank=True, help_text='Nombre del cliente final', max_length=100, null=True)),
                ('rfc_cliente_final', models.CharField(blank=True, help_text='RFC del cliente final', max_length=13, null=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['nombre_corto'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unidades',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='unidades_descuento',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='No usado - mantenido por compatibilidad', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('RH', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('PROD', 'Producción'), ('TI', 'Tecnología')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este email.'}, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='unidades_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Unidades administrativas a las que pertenece el usuario', to='accounts.unidad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad a la que pertenece el usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.unidad', verbose_name='Unidad'),
        ),
    ]
