# Generated by Django 5.0.1 on 2025-02-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_unidad_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='unidad',
            name='id_pricelist',
            field=models.IntegerField(blank=True, help_text='ID de la lista de precios para filtrar en el frontend', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Requerido. 150 caracteres o menos.', max_length=150, unique=True, verbose_name='username'),
        ),
    ]
