# Generated by Django 5.0.1 on 2025-03-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_managers_unidad_id_pricelist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='user_api',
            field=models.CharField(blank=True, help_text='ID del usuario para consultar clientes por API de odoo', max_length=5, null=True),
        ),
    ]
