# Generated by Django 5.0.1 on 2025-03-22 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_unidad_user_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del usuario de Odoo', max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(help_text='Contraseña del usuario de Odoo', max_length=100)),
                ('api_key', models.CharField(help_text='API Key del usuario de Odoo', max_length=100)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del usuario de Odoo', max_length=100)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario de Odoo está activo')),
            ],
            options={
                'verbose_name': 'Usuario de Odoo',
                'verbose_name_plural': 'Usuarios de Odoo',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='unidad',
            name='odoo_user',
            field=models.ForeignKey(blank=True, help_text='Usuario de Odoo asignado a esta unidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='accounts.odoouser'),
        ),
    ]
