# Generated by Django 5.0.1 on 2025-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_odoouser_unidad_odoo_user'),
        ('compras', '0004_categoria_alter_categoriacomprador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='categorias_compras_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Categorías de productos asignadas a este usuario para compras', related_name='usuarios_asignados', to='compras.categoria'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_comprador',
            field=models.CharField(blank=True, help_text='Nombre del comprador que identifica al usuario (si aplica)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='odoouser',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key del usuario de Odoo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='odoouser',
            name='email',
            field=models.EmailField(blank=True, help_text='Email del usuario de Odoo', max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='odoouser',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre descriptivo del usuario de Odoo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='odoouser',
            name='password',
            field=models.CharField(blank=True, help_text='Contraseña del usuario de Odoo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='razon_social',
            field=models.CharField(choices=[('MPF', 'MANUFACTURAS POST FORM'), ('SLL', 'Salmon De La Laguna S.A. de C.V.'), ('OSG', 'Operadora de Sucursales Gebesa S.A. de C.V.'), ('GNA', 'GEBESA NACIONAL')], help_text='Razón social de la unidad', max_length=3),
        ),
    ]
