# Generated by Django 5.0.1 on 2025-05-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_create_aip_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hubspot_id',
            field=models.CharField(blank=True, help_text='Owner Id de HubSpot del usuario', max_length=255, null=True, verbose_name='Owner Id de HubSpot'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(blank=True, choices=[('RH', 'Recursos Humanos'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras'), ('PROD', 'Producción'), ('TI', 'Tecnología'), ('AIP', 'AIP')], max_length=20, null=True),
        ),
    ]
