# Generated by Django 5.0.1 on 2025-05-27 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_hubspot_id'),
        ('accounts', '0015_userprofile_odoo_user_id_alter_user_area'),
    ]

    operations = [
    ]
