# Generated by Django 5.0.1 on 2025-06-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_merge_20250527_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendedor_id',
            field=models.CharField(blank=True, help_text='ID del vendedor', max_length=50, null=True, verbose_name='ID del vendedor en Odoo'),
        ),
    ]
