# Generated by Django 5.0.1 on 2025-04-11 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_load_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('almacen_id', models.IntegerField(help_text='ID del almacén en el sistema', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del almacén', max_length=100)),
                ('codigo', models.CharField(blank=True, help_text='Código del almacén', max_length=20, null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el almacén está activo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de la última actualización')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales del almacén en formato JSON', null=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, help_text='Número o identificador de la propuesta', max_length=20, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('solicitar_modificacion', 'Solicitar modificación')], default='borrador', help_text='Estado actual de la propuesta de compra', max_length=25)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización')),
                ('fecha_envio', models.DateTimeField(blank=True, help_text='Fecha de envío de la propuesta', null=True)),
                ('fecha_aprobacion_rechazo', models.DateTimeField(blank=True, help_text='Fecha de aprobación o rechazo de la propuesta', null=True)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales sobre la propuesta', null=True)),
                ('almacenes', models.ManyToManyField(help_text='Almacenes considerados en esta propuesta', related_name='propuestas_compra', to='compras.almacen')),
                ('comprador', models.ForeignKey(help_text='Comprador que genera la propuesta', on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_compra', to='compras.compradoruser')),
                ('usuario_aprobador', models.ForeignKey(blank=True, help_text='Usuario que aprobó o rechazó la propuesta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propuestas_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de Compra',
                'verbose_name_plural': 'Propuestas de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LineaPropuestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(help_text='Código del producto', max_length=50)),
                ('nombre_producto', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('unidad_medida', models.CharField(help_text='Unidad de medida del producto', max_length=20)),
                ('categoria_id', models.IntegerField(help_text='ID de la categoría del producto')),
                ('grupo', models.CharField(blank=True, help_text='Grupo del producto', max_length=100, null=True)),
                ('linea', models.CharField(blank=True, help_text='Línea del producto', max_length=100, null=True)),
                ('existencia', models.DecimalField(blank=True, decimal_places=2, help_text='Existencia actual', max_digits=15, null=True)),
                ('comprometido', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad comprometida', max_digits=15, null=True)),
                ('libre', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad libre', max_digits=15, null=True)),
                ('consumo_mensual', models.DecimalField(blank=True, decimal_places=2, help_text='Consumo mensual promedio', max_digits=15, null=True)),
                ('produccion_po_abiertos', models.DecimalField(blank=True, decimal_places=2, help_text='Producción en proceso o PO abiertos', max_digits=15, null=True)),
                ('por_registrar', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad por registrar', max_digits=15, null=True)),
                ('cantidad_propuesta', models.DecimalField(decimal_places=2, help_text='Cantidad propuesta para compra', max_digits=15)),
                ('justificacion', models.TextField(blank=True, help_text='Justificación para la compra propuesta', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propuesta', models.ForeignKey(help_text='Propuesta de compra a la que pertenece esta línea', on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='compras.propuestacompra')),
            ],
            options={
                'verbose_name': 'Línea de Propuesta de Compra',
                'verbose_name_plural': 'Líneas de Propuesta de Compra',
                'ordering': ['propuesta', 'codigo_producto'],
                'unique_together': {('propuesta', 'codigo_producto')},
            },
        ),
    ]
