# Generated by Django 5.0.1 on 2025-04-11 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_almacen_propuestacompra_lineapropuestacompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.IntegerField(help_text='ID de la categoría de productos', primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la categoría', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la categoría está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoriacomprador',
            options={'ordering': ['categoria_id'], 'verbose_name': 'Categoría de Comprador (Legado)', 'verbose_name_plural': 'Categorías de Compradores (Legado)'},
        ),
        migrations.AddField(
            model_name='compradoruser',
            name='categorias_asignadas',
            field=models.ManyToManyField(blank=True, help_text='Categorías de productos asignadas a este comprador', related_name='compradores', to='compras.categoria'),
        ),
    ]
