# Generated by Django 5.0.1 on 2025-04-11 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_categoria_alter_categoriacomprador_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaComprador',
        ),
        migrations.AlterField(
            model_name='propuestacompra',
            name='comprador',
            field=models.ForeignKey(help_text='Usuario comprador que genera la propuesta', on_delete=django.db.models.deletion.PROTECT, related_name='propuestas_compra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CompradorUser',
        ),
    ]
