# Generated by Django 5.0.1 on 2025-04-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_delete_categoriacomprador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestacompra',
            name='almacenes',
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='almacenes_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs de almacenes considerados en esta propuesta'),
        ),
        migrations.DeleteModel(
            name='Almacen',
        ),
    ]
