# Generated by Django 5.0.1 on 2025-04-14 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_remove_propuestacompra_almacenes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestacompra',
            name='almacenes_ids',
        ),
        migrations.CreateModel(
            name='ItemPropuestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Categoría del producto', max_length=100)),
                ('codigo', models.CharField(help_text='Código del producto', max_length=50)),
                ('producto', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('medida', models.CharField(help_text='Unidad de medida del producto', max_length=20)),
                ('registrar', models.DecimalField(decimal_places=2, default=0, help_text='Ya en planta pero no se ha registrado', max_digits=15)),
                ('produccion', models.DecimalField(decimal_places=2, default=0, help_text='No está en planta pero ya está pedido', max_digits=15)),
                ('cantidad_propuesta', models.DecimalField(decimal_places=2, help_text='Cantidad propuesta para compra', max_digits=15)),
                ('proveedor', models.CharField(help_text='Proveedor sugerido o default', max_length=200)),
                ('meses', models.DecimalField(decimal_places=2, help_text='Meses de cobertura (Libre + Por Registrar + En producción + Propuesta / Consumo Mensual)', max_digits=8)),
                ('comentarios', models.TextField(blank=True, help_text='Comentarios adicionales sobre este item', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('propuesta', models.ForeignKey(help_text='Propuesta de compra a la que pertenece este item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.propuestacompra')),
            ],
            options={
                'verbose_name': 'Item de Propuesta de Compra',
                'verbose_name_plural': 'Items de Propuesta de Compra',
                'db_table': 'compras_itempropuestacompra',
                'ordering': ['propuesta', 'codigo'],
                'unique_together': {('propuesta', 'codigo')},
            },
        ),
        migrations.DeleteModel(
            name='LineaPropuestaCompra',
        ),
    ]
