# Generated by Django 5.0.1 on 2025-04-21 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_lineapropuestacompra_to_itempropuestacompra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempropuestacompra',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='proveedor',
            field=models.CharField(blank=True, help_text='Proveedor principal asociado a esta propuesta', max_length=255, null=True),
        ),
    ]
