# Generated by Django 5.0.1 on 2025-04-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_remove_itempropuestacompra_proveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='cantidad_propuesta',
            field=models.DecimalField(decimal_places=6, help_text='Cantidad propuesta para compra', max_digits=15),
        ),
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='meses',
            field=models.DecimalField(decimal_places=6, help_text='Meses de cobertura (Libre + Por Registrar + En producción + Propuesta / Consumo Mensual)', max_digits=8),
        ),
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='produccion',
            field=models.DecimalField(decimal_places=6, default=0, help_text='No está en planta pero ya está pedido', max_digits=15),
        ),
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='registrar',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Ya en planta pero no se ha registrado', max_digits=15),
        ),
    ]
