# Generated by Django 5.0.1 on 2025-04-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_alter_itempropuestacompra_cantidad_propuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropuestacompra',
            name='comprometido',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Cantidad comprometida según pronóstico', max_digits=15),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='consumo_mensual',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Consumo mensual promedio según pronóstico', max_digits=15),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Costo unitario del producto según pronóstico', max_digits=15),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='existencia',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Existencia actual según pronóstico', max_digits=15),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='inv_mensuales',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Meses de inventario según pronóstico', max_digits=8),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='libre',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Cantidad libre (Existencia - Comprometido) según pronóstico', max_digits=15),
        ),
    ]
