# Generated by Django 5.0.1 on 2025-04-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_itempropuestacompra_comprometido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='meses',
            field=models.DecimalField(decimal_places=6, help_text='Meses de cobertura (Libre + Por Registrar + En producción + Propuesta / Consumo Mensual)', max_digits=12),
        ),
    ]
