# Generated by Django 5.0.1 on 2025-04-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0011_alter_itempropuestacompra_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropuestacompra',
            name='cantidad_oc',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cantidad en órdenes de compra abiertas según pronóstico', max_digits=15),
        ),
    ]
