# Generated by Django 5.0.1 on 2025-04-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_itempropuestacompra_cantidad_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestacompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('modificada_aprobada', 'Modificada y Aprobada'), ('rechazada', 'Rechazada'), ('enviada', 'Enviada a Proveedor')], default='borrador', help_text='Estado actual de la propuesta de compra', max_length=25),
        ),
    ]
