# Generated by Django 5.0.1 on 2025-04-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_alter_propuestacompra_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacompra',
            name='almacenes_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista de IDs y nombres de almacenes seleccionados para la propuesta (ej: [{"id": 1, "name": "Almacen A"}])', null=True),
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='categoria_id',
            field=models.IntegerField(blank=True, help_text='ID de la categoría seleccionada para la propuesta', null=True),
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='categoria_nombre',
            field=models.CharField(blank=True, help_text='Nombre de la categoría seleccionada para la propuesta', max_length=255, null=True),
        ),
    ]
