# Generated by Django 5.0.1 on 2025-04-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0014_propuestacompra_almacenes_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropuestacompra',
            name='proveedor_id',
            field=models.IntegerField(blank=True, help_text='ID del proveedor asignado a este item', null=True),
        ),
    ]
