# Generated by Django 5.0.1 on 2025-05-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0015_itempropuestacompra_proveedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempropuestacompra',
            name='inv_mensuales',
            field=models.DecimalField(decimal_places=6, default=0.0, help_text='Meses de inventario según pronóstico', max_digits=15),
        ),
    ]
