# Generated by Django 5.0.1 on 2025-05-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0016_alter_itempropuestacompra_inv_mensuales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propuestacompra',
            name='comentarios',
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='historial_eventos',
            field=models.JSONField(blank=True, default=list, help_text='Historial de eventos y comentarios de la propuesta'),
        ),
    ]
