# Generated by Django 5.0.1 on 2025-05-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0017_remove_propuestacompra_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacompra',
            name='fecha_registro_odoo',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que la propuesta fue registrada en Odoo', null=True, verbose_name='Fecha de Registro en Odoo'),
        ),
        migrations.AddField(
            model_name='propuestacompra',
            name='odoo_purchase_order_id',
            field=models.CharField(blank=True, help_text='ID o referencia de la Orden de Compra generada en Odoo', max_length=100, null=True, verbose_name='ID de Orden de Compra en Odoo'),
        ),
        migrations.AlterField(
            model_name='propuestacompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente Aprobación'), ('aprobada', 'Aprobada'), ('modificada_aprobada', 'Modificada y Aprobada'), ('rechazada', 'Rechazada'), ('enviada', 'Enviada a Proveedor'), ('registrada_odoo', 'Registrada en Odoo')], default='borrador', help_text='Estado actual de la propuesta de compra', max_length=25),
        ),
    ]
