# Generated by Django 5.0.1 on 2025-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0018_propuestacompra_fecha_registro_odoo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropuestacompra',
            name='medida_id',
            field=models.IntegerField(blank=True, help_text='ID de la unidad de medida en Odoo', null=True),
        ),
        migrations.AddField(
            model_name='itempropuestacompra',
            name='product_id',
            field=models.IntegerField(blank=True, help_text='ID del producto en Odoo', null=True),
        ),
    ]
