# Generated by Django 5.0.1 on 2025-05-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0019_itempropuestacompra_medida_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropuestacompra',
            name='currency_id',
            field=models.IntegerField(blank=True, default=3, help_text='ID de la moneda en Odoo', null=True),
        ),
    ]
