# Generated by Django 5.0.1 on 2025-05-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0020_itempropuestacompra_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuestacompra',
            name='odoo_response',
            field=models.JSONField(blank=True, help_text='Respuesta completa de Odoo al crear la orden de compra', null=True, verbose_name='Respuesta de Odoo'),
        ),
    ]
