# Generated by Django 5.0.1 on 2025-02-20 22:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productobundle',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='detallecotizacion',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='productobundle',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='cotizacion',
            options={},
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='atencion_a',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='codigo_vendedor',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='comentarios_internos',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='condiciones_pago',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_calle',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_ciudad',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_colonia',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_cp',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_estado',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='direccion_fiscal_numero',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='ejecutivo_ventas',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='email_representante',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='folio_cotizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='lugar_entrega',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='motivo_autorizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='razon_social',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='requiere_autorizacion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='rfc',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='telefono_representante',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='tiempo_entrega',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='tipo_cambio',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='vigencia_dias',
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='email_vendedor',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='logistica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal_mobiliario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='telefono_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proyectista',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='unidad_facturacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ConfiguracionPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('vigencia', models.CharField(blank=True, max_length=255, null=True)),
                ('condiciones_pago', models.TextField(blank=True, null=True)),
                ('mostrar_clave', models.BooleanField(default=True)),
                ('mostrar_precio_lista', models.BooleanField(default=True)),
                ('mostrar_precio_descuento', models.BooleanField(default=True)),
                ('mostrar_logistica', models.BooleanField(default=True)),
                ('mostrar_descuento_total', models.BooleanField(default=True)),
                ('cotizacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_pdf', to='cotizador.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_kit', models.BooleanField(default=False)),
                ('especial', models.BooleanField(default=False)),
                ('clave', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('linea', models.CharField(blank=True, max_length=100, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('grupo', models.CharField(blank=True, max_length=100, null=True)),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precio_lista', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('precio_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('margen', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizador.cotizacion')),
            ],
        ),
        migrations.DeleteModel(
            name='Bundle',
        ),
        migrations.DeleteModel(
            name='DetalleCotizacion',
        ),
        migrations.DeleteModel(
            name='ProductoBundle',
        ),
    ]
