# Generated by Django 5.0.1 on 2025-02-20 22:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_remove_productobundle_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
