# Generated by Django 5.0.1 on 2025-02-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_alter_cotizacion_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
