# Generated by Django 5.0.1 on 2025-02-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_productocotizacion_porcentaje_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_proyecto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
