# Generated by Django 5.0.1 on 2025-02-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_cotizacion_fecha_proyecto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='productocotizacion',
            options={'verbose_name': 'Producto de Cotización', 'verbose_name_plural': 'Productos de Cotización'},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='logistica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal_mobiliario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='importe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='margen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_lista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
