# Generated by Django 5.0.1 on 2025-02-21 03:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
