# Generated by Django 5.0.1 on 2025-02-21 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_alter_cotizacion_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_rechazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='motivo',
            field=models.TextField(blank=True, help_text='Motivo de rechazo o cancelación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_aprobacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_creacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_envio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario_rechazo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_rechazadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='email_vendedor',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='persona_contacto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proyectista',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='proyecto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_vendedor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='unidad_facturacion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='vendedor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
