# Generated by Django 5.0.1 on 2025-02-21 04:16

from django.db import migrations

def update_null_to_empty(apps, schema_editor):
    Cotizacion = apps.get_model('cotizador', 'Cotizacion')
    
    # Actualizar todos los registros que tengan campos nulos a string vacío
    Cotizacion.objects.filter(folio__isnull=True).update(folio='')
    Cotizacion.objects.filter(proyecto__isnull=True).update(proyecto='')
    Cotizacion.objects.filter(cliente__isnull=True).update(cliente='')
    Cotizacion.objects.filter(persona_contacto__isnull=True).update(persona_contacto='')
    Cotizacion.objects.filter(email_cliente__isnull=True).update(email_cliente='')
    Cotizacion.objects.filter(telefono_cliente__isnull=True).update(telefono_cliente='')
    Cotizacion.objects.filter(vendedor__isnull=True).update(vendedor='')
    Cotizacion.objects.filter(email_vendedor__isnull=True).update(email_vendedor='')
    Cotizacion.objects.filter(telefono_vendedor__isnull=True).update(telefono_vendedor='')
    Cotizacion.objects.filter(proyectista__isnull=True).update(proyectista='')
    Cotizacion.objects.filter(unidad_facturacion__isnull=True).update(unidad_facturacion='')
    Cotizacion.objects.filter(motivo__isnull=True).update(motivo='')

class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.RunPython(update_null_to_empty),
    ]
