# Generated by Django 5.0.1 on 2025-02-21 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_update_nulls'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mostrar_clave',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mostrar_descuento_total',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mostrar_logistica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mostrar_precio_descuento',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='mostrar_precio_lista',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vigencia',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='ConfiguracionPDF',
        ),
    ]
