# Generated by Django 5.0.1 on 2025-02-21 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0012_remove_cotizacion_fecha_aprobacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocotizacion',
            name='cotizacion',
            field=models.ForeignKey(db_column='cotizacion_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizador.cotizacion', to_field='uuid'),
        ),
    ]
