# Generated by Django 5.0.1 on 2025-02-21 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0014_alter_productocotizacion_cotizacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttemplate',
            options={'managed': True},
        ),
    ]
