# Generated by Django 5.0.1 on 2025-02-25 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0015_alter_producttemplate_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCache',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('reference_mask', models.CharField(max_length=255)),
                ('type_id', models.IntegerField(null=True)),
                ('family_id', models.IntegerField(null=True)),
                ('line_id', models.IntegerField(null=True)),
                ('group_id', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('is_line', models.BooleanField(default=True)),
                ('description_sale', models.TextField(null=True)),
                ('default_code', models.CharField(max_length=64, null=True)),
                ('type_name', models.CharField(max_length=255, null=True)),
                ('family_name', models.CharField(max_length=255, null=True)),
                ('line_name', models.CharField(max_length=255, null=True)),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('image_url', models.URLField(max_length=512, null=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Supabase',
                'verbose_name_plural': 'Productos Supabase',
                'db_table': 'products_cache',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='family',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.productfamily'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.productgroup'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='last_sync',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.productline'),
        ),
        migrations.AddField(
            model_name='producttemplate',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cotizador.producttype'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['name'], name='idx_name'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['reference_mask'], name='idx_ref_mask'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['is_line', 'active'], name='idx_line_active'),
        ),
        migrations.AddIndex(
            model_name='producttemplate',
            index=models.Index(fields=['type', 'family', 'line', 'group'], name='idx_product_hierarchy'),
        ),
        migrations.AlterModelTable(
            name='producttemplate',
            table='cotizador_product_template',
        ),
    ]
