# Generated by Django 5.0.1 on 2025-03-04 15:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0016_productscache_cotizacion_total_descuento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productocotizacion',
            name='kit_padre_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productocotizacion',
            name='kit_uuid',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='productocotizacion',
            name='mostrar_en_cotizacion',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_unitario_con_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kits_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kit',
                'verbose_name_plural': 'Kits',
            },
        ),
        migrations.CreateModel(
            name='KitProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_mask', models.CharField(db_index=True, max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_lista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('orden', models.IntegerField(default=0)),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cotizador.kit')),
            ],
            options={
                'verbose_name': 'Producto de Kit',
                'verbose_name_plural': 'Productos de Kit',
                'ordering': ['orden', 'id'],
                'unique_together': {('kit', 'reference_mask')},
            },
        ),
    ]
