# Generated by Django 5.0.1 on 2025-03-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0017_productocotizacion_kit_padre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizadorimagenproducto',
            name='clave_padre',
            field=models.CharField(db_index=True, help_text='Clave del producto que coincide con reference_mask de ProductTemplate', max_length=255),
        ),
    ]
