# Generated by Django 5.0.1 on 2025-03-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0021_custom_kitproducto_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitproducto',
            old_name='reference_mask',
            new_name='clave',
        ),
        migrations.AlterUniqueTogether(
            name='kitproducto',
            unique_together={('kit', 'clave')},
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='es_opcional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='familia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='linea',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='mostrar_en_kit',
            field=models.BooleanField(default=True),
        ),
    ]
