# Generated by Django 5.0.1 on 2025-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0027_add_tag_to_kit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='name_partner',
            field=models.CharField(default='', help_text='Nombre del cliente', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='producttemplate',
            table='product_template',
        ),
    ]
