# Generated by Django 5.0.1 on 2025-03-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0029_manual_add_tag_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocotizacion',
            name='importe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_lista',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
