# Generated by Django 5.0.1 on 2025-03-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0029_manual_add_tag_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='odoo_so',
            field=models.CharField(blank=True, help_text='Número de orden de venta en Odoo', max_length=50, null=True),
        ),
    ]
