# Generated by Django 5.0.1 on 2025-03-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0030_alter_productocotizacion_importe_and_more'),
        ('cotizador', '0030_cotizacion_odoo_so'),
    ]

    operations = [
    ]
