# Generated by Django 5.0.1 on 2025-04-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0032_productocotizacion_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kit',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
