# Generated by Django 5.0.1 on 2025-04-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0033_alter_kit_imagen_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitproducto',
            name='especial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='padre',
            field=models.BooleanField(default=True),
        ),
    ]
