# Generated by Django 5.0.1 on 2025-04-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0034_kitproducto_especial_kitproducto_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitproducto',
            name='padre',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
