# Generated by Django 5.0.1 on 2025-04-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0035_alter_kitproducto_padre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productocotizacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
