# Generated by Django 5.0.1 on 2025-04-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0036_alter_productocotizacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
