# Generated by Django 5.0.1 on 2025-04-22 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0037_cotizacion_vendedor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='total_descuento',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='kit',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=16),
        ),
    ]
