# Generated by Django 5.0.1 on 2025-04-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0038_alter_cotizacion_total_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='logistica',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal_mobiliario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='total_general',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kit',
            name='costo_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kit',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kit',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kit',
            name='valor_unitario_con_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='importe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='precio_lista',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
