# Generated by Django 5.0.1 on 2025-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0039_alter_cotizacion_iva_alter_cotizacion_logistica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='hs_deal_id',
            field=models.CharField(blank=True, help_text='ID del negocio en HubSpot', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kitproducto',
            name='route_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productocotizacion',
            name='route_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
