# Generated by Django 5.0.1 on 2025-05-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0041_auto_20250425_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitproducto',
            name='costo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kitproducto',
            name='importe',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kitproducto',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kitproducto',
            name='precio_descuento',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='kitproducto',
            name='precio_lista',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
    ]
