# Generated by Django 5.0.1 on 2025-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0042_alter_kitproducto_costo_alter_kitproducto_importe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='unidad_facturacion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
