# Generated by Django 5.0.1 on 2025-06-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0043_alter_cotizacion_unidad_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitproducto',
            name='clave',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productocotizacion',
            name='clave',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
