# Generated by Django 5.0.1 on 2025-05-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HubspotEngagement',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('engagement_id', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_ids', models.JSONField(blank=True, null=True)),
                ('company_ids', models.JSONField(blank=True, null=True)),
                ('deal_ids', models.JSONField(blank=True, null=True)),
                ('last_sync_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('body_preview', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': '"analytics"."hubspot_engagements"',
                'managed': False,
            },
        ),
    ]
